{% set name = "printo" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/printo-{{ version }}.tar.gz
  sha256: d42760f50f7b5ac1c3212a9da7ab25c7e96659be1af3e1fd2fd086fe8611ea5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools ==68.0.0
    - pip
  run:
    - python >=3.7

test:
  imports:
    - printo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pomponchik/printo
  summary: Print objects with data beautifully
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
